GET https://cms.xprtz.dev/api/global-settings?filters[site][$eq]=dotnet&populate[pages][fields][0]=title_website&populate[pages][fields][1]=description&pagination[pageSize]=10&pagination[page]=1&status=published
###
GET http://localhost:1337/api/global-settings?filters[site][$eq]=dotnet&populate[pages][fields][0]=title_website&populate[pages][fields][1]=description&pagination[pageSize]=10&pagination[page]=1&status=published
###
GET http://localhost:1337/api/homepages?filters[site][$eq]=dotnet
###
GET http://localhost:1337/api/pages/c238qp5ivwwvs6ws2f1ys9v3?filters[site][$eq]=dotnet
###
GET http://localhost:1337/api/articles?filters[site][$eq]=dotnet&pagination[pageSize]=2&pagination[page]=2
