GET https://cms.xprtz.dev/api/global-settings?filters[site][$eq]=dotnet&populate[pages][fields][0]=title_website&populate[pages][fields][1]=description&pagination[pageSize]=10&pagination[page]=1&status=published
###
GET http://localhost:1337/api/global-settings?filters[site][$eq]=dotnet&populate[pages][fields][0]=title_website&populate[pages][fields][1]=description&pagination[pageSize]=10&pagination[page]=1&status=published
