name: Continuous delivery workflow
run-name: Deploying website to the production environment
concurrency: continuous-delivery-${{ github.ref_name }}

on:
  workflow_dispatch:
  push:
    branches: [main]

permissions:
  id-token: write
  contents: read

jobs:
  apply-infrastructure:
    name: Apply infrastructure
    uses: ./.github/workflows/reusable-apply-infrastructure.yaml
    with:
      environment: production
      deployDns: true
    secrets: inherit

  build-cloud-application:
    name: Build XPRTZ Cloud application
    uses: ./.github/workflows/reusable-build-application.yaml
    with:
      application: cloud
    needs: [apply-infrastructure]

  deploy-cloud-application:
    name: Deploy XPRTZ Cloud application
    uses: ./.github/workflows/reusable-deploy-application.yaml
    with:
      application: cloud
      storageAccount: ${{ needs.apply-infrastructure.outputs.cloudStorageAccount }}
      environment: production
    needs: [apply-infrastructure, build-cloud-application]
    secrets: inherit

  build-dotnet-application:
    name: Build XPRTZ .NET application
    uses: ./.github/workflows/reusable-build-application.yaml
    with:
      application: dotnet
    needs: [apply-infrastructure]

  deploy-dotnet-application:
    name: Deploy XPRTZ .NET application
    uses: ./.github/workflows/reusable-deploy-application.yaml
    with:
      application: dotnet
      storageAccount: ${{ needs.apply-infrastructure.outputs.dotnetStorageAccount }}
      environment: production
    needs: [apply-infrastructure, build-dotnet-application]
    secrets: inherit

  build-landing-application:
    name: Build XPRTZ Landing application
    uses: ./.github/workflows/reusable-build-application.yaml
    with:
      application: landing
    needs: [apply-infrastructure]

  deploy-landing-application:
    name: Deploy XPRTZ Landing application
    uses: ./.github/workflows/reusable-deploy-application.yaml
    with:
      application: landing
      storageAccount: ${{ needs.apply-infrastructure.outputs.landingStorageAccount }}
      environment: production
    needs: [apply-infrastructure, build-landing-application]
    secrets: inherit
