name: Continuous integration workflow for XPRTZ.net
run-name: Continuous Integration - XPRTZ.net - ${{ github.ref_name }}
concurrency: ci-dotnet

on:
  workflow_dispatch:
  push:
    branches-ignore:
      - main
    paths:
      - ".github/workflows/**"
      - "apps/dotnet/**"

permissions:
  id-token: write
  contents: read

jobs:
  build-dotnet-application:
    uses: ./.github/workflows/reusable-build-application.yaml
    with:
      application: dotnet
      upload-artifcats: false
