name: Continuous delivery XPRTZ website workflow
run-name: Deploying XPRTZ website to the production environment
concurrency: continuous-delivery-dotnet-${{ github.ref_name }}

on:
  workflow_dispatch:
  push:
    branches: [main]
    paths:
      - 'apps/dotnet/**'
      - 'libs/**'
      - 'infrastructure/**'
      - '.github/**'

permissions:
  id-token: write
  contents: read

jobs:
  build-dotnet-application:
    name: Build XPRTZ website
    uses: ./.github/workflows/reusable-build-application.yaml
    with:
      application: dotnet

  apply-infrastructure-preview:
    name: Apply infrastructure on preview
    uses: ./.github/workflows/reusable-apply-infrastructure.yaml
    with:
      environment: preview
      application: dotnet
    needs: [build-dotnet-application]
    secrets: inherit

  deploy-dotnet-application-preview:
    name: Deploy XPRTZ website on preview
    uses: ./.github/workflows/reusable-deploy-application.yaml
    with:
      application: dotnet
      storageAccount: ${{ needs.apply-infrastructure.outputs.storageAccount }}
      environment: preview
    needs: [build-dotnet-application, apply-infrastructure-preview]
    secrets: inherit
