name: PR workflow
run-name: ${{ github.actor }} is building the website

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened]

permissions:
      id-token: write
      contents: read
jobs:
  CI:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      # - name: Deploy infrastructure
      #   uses: azure/arm-deploy@v1
      #   with:
      #     scope: subscription
      #     region: westeurope
      #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     template: ./deploy/infrastructure.bicep
      #     failOnStdErr: false

      - name: Inject slug/short variables
        uses: rlespinasse/github-slug-action@v4
        with:
          slug-maxlength: 16

      - name: Login to ACR
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az acr login -n ${{ secrets.REGISTRY_NAME }}

      - name: Build and push container image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.REGISTRY_NAME }}.azurecr.io/website:${{ env.GITHUB_REF_NAME_SLUG }}

      # - name: Deploy website
      #   uses: azure/arm-deploy@v1
      #   with:
      #     scope: subscription
      #     region: westeurope
      #     subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      #     template: ./deploy/main.bicep
      #     parameters: imageTag=${{ env.GITHUB_REF_SLUG }}
      #     failOnStdErr: false

