name: Pull request workflow
run-name: Running pull request flow for ${{ github.base_ref }}
concurrency: pull-request

on:
  workflow_dispatch:
  pull_request:
    types: [opened, synchronize, reopened, closed]

jobs:
  apply-pull-request-infrastructure:
    uses: ./.github/workflows/reusable-apply-infrastructure.yaml
    with:
      azureEnvironment: ${{ github.run_id }}
      githubEnvironment: preview
      tearDown: true
    secrets: inherit

  build-cloud-application:
    uses: ./.github/workflows/reusable-build-application.yaml
    with:
      application: cloud
    needs: [apply-pull-request-infrastructure]

  deploy-cloud-application:
    uses: ./.github/workflows/reusable-deploy-application.yaml
    with:
      application: cloud
      storageAccount: ""
    needs: [build-cloud-application]

  build-dotnet-application:
    uses: ./.github/workflows/reusable-build-application.yaml
    with:
      application: dotnet
    needs: [apply-pull-request-infrastructure]

  deploy-dotnet-application:
    uses: ./.github/workflows/reusable-deploy-application.yaml
    with:
      application: dotnet
      storageAccount: ""
    needs: [build-dotnet-application]
