name: "[Reusable workflow] Build application"
run-name: Building application for ${{ inputs.application }}
concurrency: build-${{ inputs.application }}-${{ github.ref_name }}-${{ github.event_name }}

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string
      upload-artifcats:
        type: boolean
        default: true

env:
  PUBLIC_STRAPI_URL: ${{ vars.PUBLIC_STRAPI_URL }}
  PUBLIC_IMAGES_URL: ${{ vars.PUBLIC_IMAGES_URL }}
  PUBLIC_SITE: ${{ inputs.application }}

jobs:
  build-application:
    name: Build ${{ inputs.application }}
    defaults:
      run:
        working-directory: ./apps/${{ inputs.application }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: show env
        run: env

      - name: npm install
        run: npm install

      - name: Build application
        run: npm run build

      - name: Upload build artifacts
        if: ${{ inputs.upload-artifcats }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.application }}-dist
          path: ~/work/website/website/apps/${{ inputs.application }}/dist/
