name: "[Reusable workflow] Build application"
run-name: Building application for ${{ inputs.application }}
concurrency: build-${{ inputs.application }}

on:
  workflow_call:
    inputs:
      application:
        required: true
        type: string

jobs:
  build-application:
    name: Build ${{ inputs.application }}
    defaults:
      run:
        working-directory: ./apps/${{ inputs.application }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: lts
          cache: "pnpm"

      - name: pnpm install
        run: pnpm install

      - name: Build application
        run: pnpm run build:${{ inputs.application }}

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.application }}-dist
          path: ./dist
