name: "[Reusable workflow] Destroy infrastructure"
concurrency: destroy-infrastructure-${{ github.ref_name }}

on:
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      resourcegroup:
        required: true
        type: string

jobs:
  destroy-infrastructure:
    name: Destroy infrastructure
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Azure login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Remove resource group
        uses: azure/cli@v2
        with:
          azcliversion: latest
          inlineScript: az group delete --name ${{ inputs.resourcegroup }} --yes
