name: CI/CD workflow
run-name: ${{ github.actor }} is building the website

on:
  workflow_dispatch:
  pull_request:
    branches: [ main ]
  push:
    branches: [ main ]

permissions:
      id-token: write
      contents: read
jobs:
  Preview:
    runs-on: ubuntu-latest
    environment: preview
    steps:
      - uses: actions/checkout@main

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}


      - name: Show subscription details
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show

      - name: Deploy infrastructure
        uses: azure/arm-deploy@v1
        with:
          scope: subscription
          region: westeurope
          subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          template: ./deploy/infrastructure.bicep
          failOnStdErr: false

  Production:
    needs: Preview
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Show subscription details
        uses: azure/CLI@v1
        with:
          azcliversion: latest
          inlineScript: |
            az account show
